
name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build Debug APK
        run: cd parentjoy && ./gradlew assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: parentjoy-apk
          path: parentjoy/app/build/outputs/apk/debug/app-debug.apk

      - name: Build Release AAB
        run: cd parentjoy && ./gradlew bundleRelease

      - name: Upload release AAB
        uses: actions/upload-artifact@v4
        with:
          name: parentjoy-aab
          path: parentjoy/app/build/outputs/bundle/release/*.aab
