name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Show repository structure
        run: ls -R

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Release AAB
        run: ./gradlew bundleRelease
